export const SET_DISPLAY_RANGE = 'SET_DISPLAY_RANGE';
export const FETCH_METEORITE_DATA = 'FETCH_METEORITE_DATA';
export const PUT_METEORITE_DATA = 'PUT_METEORITE_DATA';
export const ADD_HISTORY_RECORD = 'ADD_HISTORY_RECORD';
